/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BodyWeightEntry { 'weight' : bigint, 'date' : string }
export interface ClientProfile {
  'username' : string,
  'emailOrNickname' : [] | [string],
}
export interface Exercise {
  'name' : string,
  'sets' : bigint,
  'setWeights' : Array<bigint>,
  'restTime' : bigint,
  'repetitions' : bigint,
}
export interface ExerciseLog {
  'actualRepetitions' : bigint,
  'actualSetWeights' : Array<bigint>,
  'name' : string,
  'sets' : bigint,
  'actualSets' : bigint,
  'setWeights' : Array<bigint>,
  'restTime' : bigint,
  'repetitions' : bigint,
}
export interface ExercisePerformance { 'date' : string, 'exercise' : Exercise }
export interface UserProfile {
  'username' : string,
  'role' : string,
  'emailOrNickname' : [] | [string],
  'codicePT' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Workout {
  'creator' : string,
  'name' : string,
  'exercises' : Array<Exercise>,
  'clientUsername' : string,
  'comments' : string,
}
export interface WorkoutLog {
  'date' : string,
  'exercises' : Array<ExerciseLog>,
  'completed' : boolean,
  'clientNotes' : [] | [string],
  'clientUsername' : string,
  'comments' : string,
  'workoutName' : string,
}
export interface WorkoutProgress {
  'date' : string,
  'exercises' : Array<Exercise>,
  'comments' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBodyWeightEntry' : ActorMethod<[string, bigint, string], undefined>,
  'addExercisePerformance' : ActorMethod<[string, Exercise, string], undefined>,
  'addWorkoutProgress' : ActorMethod<[string, WorkoutProgress], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateClient' : ActorMethod<[string, string], undefined>,
  'authenticateTrainer' : ActorMethod<[string], bigint>,
  'createClientWorkout' : ActorMethod<
    [string, string, Array<Exercise>, string],
    undefined
  >,
  'createOwnWorkout' : ActorMethod<
    [string, Array<Exercise>, string],
    undefined
  >,
  'getBodyWeightHistory' : ActorMethod<[string], Array<BodyWeightEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientInfo' : ActorMethod<[string], [string, string, [] | [string]]>,
  'getClientProfile' : ActorMethod<[string], ClientProfile>,
  'getClientProgress' : ActorMethod<[string], Array<WorkoutProgress>>,
  'getClientsForTrainer' : ActorMethod<[], Array<ClientProfile>>,
  'getExercisePerformanceHistory' : ActorMethod<
    [string],
    Array<ExercisePerformance>
  >,
  'getTrainerPtCode' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkoutLogsForClient' : ActorMethod<[string], Array<WorkoutLog>>,
  'getWorkoutsForClient' : ActorMethod<[string], Array<Workout>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logWorkoutCompletion' : ActorMethod<[WorkoutLog, string], undefined>,
  'registerClient' : ActorMethod<
    [string, string, [] | [string], bigint],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setClientHeight' : ActorMethod<[string, bigint], undefined>,
  'updateClientEmail' : ActorMethod<[string, string], undefined>,
  'updateClientWorkout' : ActorMethod<
    [string, string, Array<Exercise>, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];