/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'sets' : IDL.Nat,
  'setWeights' : IDL.Vec(IDL.Nat),
  'restTime' : IDL.Nat,
  'repetitions' : IDL.Nat,
});
export const WorkoutProgress = IDL.Record({
  'date' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
  'comments' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BookingUpdate = IDL.Record({
  'clientName' : IDL.Text,
  'clientEmail' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Text,
  'isConfirmed' : IDL.Bool,
  'dateTime' : Time,
});
export const BodyWeightEntry = IDL.Record({
  'weight' : IDL.Nat,
  'date' : IDL.Text,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'clientName' : IDL.Text,
  'clientEmail' : IDL.Text,
  'trainerPrincipal' : IDL.Principal,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Text,
  'isConfirmed' : IDL.Bool,
  'dateTime' : Time,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'role' : IDL.Text,
  'emailOrNickname' : IDL.Opt(IDL.Text),
  'codicePT' : IDL.Opt(IDL.Text),
});
export const ClientProfile = IDL.Record({
  'username' : IDL.Text,
  'emailOrNickname' : IDL.Opt(IDL.Text),
});
export const ExercisePerformance = IDL.Record({
  'date' : IDL.Text,
  'exercise' : Exercise,
});
export const ExerciseLog = IDL.Record({
  'actualRepetitions' : IDL.Nat,
  'actualSetWeights' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'sets' : IDL.Nat,
  'actualSets' : IDL.Nat,
  'setWeights' : IDL.Vec(IDL.Nat),
  'restTime' : IDL.Nat,
  'repetitions' : IDL.Nat,
});
export const WorkoutLog = IDL.Record({
  'date' : IDL.Text,
  'exercises' : IDL.Vec(ExerciseLog),
  'completed' : IDL.Bool,
  'clientNotes' : IDL.Opt(IDL.Text),
  'clientUsername' : IDL.Text,
  'comments' : IDL.Text,
  'workoutName' : IDL.Text,
});
export const Workout = IDL.Record({
  'creator' : IDL.Text,
  'name' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
  'clientUsername' : IDL.Text,
  'comments' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBodyWeightEntry' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addExercisePerformance' : IDL.Func([IDL.Text, Exercise, IDL.Text], [], []),
  'addWorkoutProgress' : IDL.Func([IDL.Text, WorkoutProgress], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateClient' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'authenticateTrainer' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createBooking' : IDL.Func([BookingUpdate], [IDL.Nat], []),
  'createClientWorkout' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(Exercise), IDL.Text],
      [],
      [],
    ),
  'createOwnWorkout' : IDL.Func(
      [IDL.Text, IDL.Vec(Exercise), IDL.Text],
      [],
      [],
    ),
  'deleteBooking' : IDL.Func([IDL.Nat], [], []),
  'getBodyWeightHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BodyWeightEntry)],
      ['query'],
    ),
  'getBookingsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientInfo' : IDL.Func(
      [IDL.Text],
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getClientProfile' : IDL.Func([IDL.Text], [ClientProfile], ['query']),
  'getClientProgress' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkoutProgress)],
      ['query'],
    ),
  'getClientsForTrainer' : IDL.Func([], [IDL.Vec(ClientProfile)], ['query']),
  'getConfirmedAppointmentsForClient' : IDL.Func(
      [],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getExercisePerformanceHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExercisePerformance)],
      ['query'],
    ),
  'getTrainerPtCode' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkoutLogsForClient' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkoutLog)],
      ['query'],
    ),
  'getWorkoutsForClient' : IDL.Func([IDL.Text], [IDL.Vec(Workout)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWorkoutCompletion' : IDL.Func([WorkoutLog, IDL.Text], [], []),
  'registerClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
      [],
      [],
    ),
  'requestAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setClientHeight' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateBooking' : IDL.Func([IDL.Nat, BookingUpdate], [], []),
  'updateClientEmail' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateTrainerCode' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateWorkout' : IDL.Func([IDL.Text, IDL.Vec(Exercise), IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Exercise = IDL.Record({
    'name' : IDL.Text,
    'sets' : IDL.Nat,
    'setWeights' : IDL.Vec(IDL.Nat),
    'restTime' : IDL.Nat,
    'repetitions' : IDL.Nat,
  });
  const WorkoutProgress = IDL.Record({
    'date' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
    'comments' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookingUpdate = IDL.Record({
    'clientName' : IDL.Text,
    'clientEmail' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Text,
    'isConfirmed' : IDL.Bool,
    'dateTime' : Time,
  });
  const BodyWeightEntry = IDL.Record({ 'weight' : IDL.Nat, 'date' : IDL.Text });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'clientName' : IDL.Text,
    'clientEmail' : IDL.Text,
    'trainerPrincipal' : IDL.Principal,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Text,
    'isConfirmed' : IDL.Bool,
    'dateTime' : Time,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'role' : IDL.Text,
    'emailOrNickname' : IDL.Opt(IDL.Text),
    'codicePT' : IDL.Opt(IDL.Text),
  });
  const ClientProfile = IDL.Record({
    'username' : IDL.Text,
    'emailOrNickname' : IDL.Opt(IDL.Text),
  });
  const ExercisePerformance = IDL.Record({
    'date' : IDL.Text,
    'exercise' : Exercise,
  });
  const ExerciseLog = IDL.Record({
    'actualRepetitions' : IDL.Nat,
    'actualSetWeights' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'sets' : IDL.Nat,
    'actualSets' : IDL.Nat,
    'setWeights' : IDL.Vec(IDL.Nat),
    'restTime' : IDL.Nat,
    'repetitions' : IDL.Nat,
  });
  const WorkoutLog = IDL.Record({
    'date' : IDL.Text,
    'exercises' : IDL.Vec(ExerciseLog),
    'completed' : IDL.Bool,
    'clientNotes' : IDL.Opt(IDL.Text),
    'clientUsername' : IDL.Text,
    'comments' : IDL.Text,
    'workoutName' : IDL.Text,
  });
  const Workout = IDL.Record({
    'creator' : IDL.Text,
    'name' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
    'clientUsername' : IDL.Text,
    'comments' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBodyWeightEntry' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addExercisePerformance' : IDL.Func([IDL.Text, Exercise, IDL.Text], [], []),
    'addWorkoutProgress' : IDL.Func([IDL.Text, WorkoutProgress], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateClient' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'authenticateTrainer' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createBooking' : IDL.Func([BookingUpdate], [IDL.Nat], []),
    'createClientWorkout' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(Exercise), IDL.Text],
        [],
        [],
      ),
    'createOwnWorkout' : IDL.Func(
        [IDL.Text, IDL.Vec(Exercise), IDL.Text],
        [],
        [],
      ),
    'deleteBooking' : IDL.Func([IDL.Nat], [], []),
    'getBodyWeightHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BodyWeightEntry)],
        ['query'],
      ),
    'getBookingsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientInfo' : IDL.Func(
        [IDL.Text],
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getClientProfile' : IDL.Func([IDL.Text], [ClientProfile], ['query']),
    'getClientProgress' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkoutProgress)],
        ['query'],
      ),
    'getClientsForTrainer' : IDL.Func([], [IDL.Vec(ClientProfile)], ['query']),
    'getConfirmedAppointmentsForClient' : IDL.Func(
        [],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getExercisePerformanceHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExercisePerformance)],
        ['query'],
      ),
    'getTrainerPtCode' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkoutLogsForClient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkoutLog)],
        ['query'],
      ),
    'getWorkoutsForClient' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Workout)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWorkoutCompletion' : IDL.Func([WorkoutLog, IDL.Text], [], []),
    'registerClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Nat],
        [],
        [],
      ),
    'requestAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setClientHeight' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateBooking' : IDL.Func([IDL.Nat, BookingUpdate], [], []),
    'updateClientEmail' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateTrainerCode' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateWorkout' : IDL.Func([IDL.Text, IDL.Vec(Exercise), IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };