/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ExercisePerformance {
    date: string;
    exercise: Exercise;
}
export interface Exercise {
    name: string;
    sets: bigint;
    setWeights: Array<bigint>;
    restTime: bigint;
    repetitions: bigint;
}
export interface WorkoutLog {
    date: string;
    exercises: Array<ExerciseLog>;
    completed: boolean;
    clientNotes?: string;
    clientUsername: string;
    comments: string;
    workoutName: string;
}
export type Time = bigint;
export interface BodyWeightEntry {
    weight: bigint;
    date: string;
}
export interface ClientProfile {
    username: string;
    emailOrNickname?: string;
}
export interface Booking {
    id: bigint;
    clientName: string;
    clientEmail: string;
    trainerPrincipal: Principal;
    durationMinutes: bigint;
    notes: string;
    isConfirmed: boolean;
    dateTime: Time;
}
export interface Workout {
    creator: string;
    name: string;
    exercises: Array<Exercise>;
    clientUsername: string;
    comments: string;
}
export interface BookingUpdate {
    clientName: string;
    clientEmail: string;
    durationMinutes: bigint;
    notes: string;
    isConfirmed: boolean;
    dateTime: Time;
}
export interface WorkoutProgress {
    date: string;
    exercises: Array<Exercise>;
    comments: string;
}
export interface UserProfile {
    username: string;
    role: string;
    emailOrNickname?: string;
    codicePT?: string;
}
export interface ExerciseLog {
    actualRepetitions: bigint;
    actualSetWeights: Array<bigint>;
    name: string;
    sets: bigint;
    actualSets: bigint;
    setWeights: Array<bigint>;
    restTime: bigint;
    repetitions: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBodyWeightEntry(username: string, weight: bigint, date: string): Promise<void>;
    addExercisePerformance(username: string, exercise: Exercise, date: string): Promise<void>;
    addWorkoutProgress(username: string, progress: WorkoutProgress): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    authenticateClient(username: string, codicePT: string): Promise<void>;
    authenticateTrainer(password: string): Promise<bigint>;
    createBooking(booking: BookingUpdate): Promise<bigint>;
    createClientWorkout(clientUsername: string, name: string, exercises: Array<Exercise>, comments: string): Promise<void>;
    createOwnWorkout(name: string, exercises: Array<Exercise>, comments: string): Promise<void>;
    deleteBooking(bookingId: bigint): Promise<void>;
    getBodyWeightHistory(username: string): Promise<Array<BodyWeightEntry>>;
    getBookingsByDateRange(startTime: Time, endTime: Time): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClientInfo(username: string): Promise<[string, string, string | null]>;
    getClientProfile(username: string): Promise<ClientProfile>;
    getClientProgress(username: string): Promise<Array<WorkoutProgress>>;
    getClientsForTrainer(): Promise<Array<ClientProfile>>;
    getConfirmedAppointmentsForClient(): Promise<Array<Booking>>;
    getExercisePerformanceHistory(username: string): Promise<Array<ExercisePerformance>>;
    getTrainerPtCode(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkoutLogsForClient(username: string): Promise<Array<WorkoutLog>>;
    getWorkoutsForClient(clientUsername: string): Promise<Array<Workout>>;
    isCallerAdmin(): Promise<boolean>;
    logWorkoutCompletion(log: WorkoutLog, workoutId: string): Promise<void>;
    registerClient(username: string, codicePT: string, emailOrNickname: string | null, trainerCode: bigint): Promise<void>;
    requestAppointment(clientName: string, clientEmail: string, dateTime: Time, durationMinutes: bigint, notes: string): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setClientHeight(username: string, height: bigint): Promise<void>;
    updateBooking(bookingId: bigint, updatedBooking: BookingUpdate): Promise<void>;
    updateClientEmail(username: string, newEmail: string): Promise<void>;
    updateTrainerCode(currentCode: string, newCode: string): Promise<void>;
    updateWorkout(workoutId: string, exercises: Array<Exercise>, comments: string): Promise<void>;
}
import type { ClientProfile as _ClientProfile, ExerciseLog as _ExerciseLog, UserProfile as _UserProfile, UserRole as _UserRole, WorkoutLog as _WorkoutLog } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBodyWeightEntry(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBodyWeightEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBodyWeightEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async addExercisePerformance(arg0: string, arg1: Exercise, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExercisePerformance(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExercisePerformance(arg0, arg1, arg2);
            return result;
        }
    }
    async addWorkoutProgress(arg0: string, arg1: WorkoutProgress): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkoutProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkoutProgress(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async authenticateClient(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateClient(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateClient(arg0, arg1);
            return result;
        }
    }
    async authenticateTrainer(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateTrainer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateTrainer(arg0);
            return result;
        }
    }
    async createBooking(arg0: BookingUpdate): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return result;
        }
    }
    async createClientWorkout(arg0: string, arg1: string, arg2: Array<Exercise>, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createClientWorkout(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClientWorkout(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createOwnWorkout(arg0: string, arg1: Array<Exercise>, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOwnWorkout(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOwnWorkout(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async getBodyWeightHistory(arg0: string): Promise<Array<BodyWeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBodyWeightHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBodyWeightHistory(arg0);
            return result;
        }
    }
    async getBookingsByDateRange(arg0: Time, arg1: Time): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByDateRange(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientInfo(arg0: string): Promise<[string, string, string | null]> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientInfo(arg0);
                return [
                    result[0],
                    result[1],
                    from_candid_opt_n6(this._uploadFile, this._downloadFile, result[2])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientInfo(arg0);
            return [
                result[0],
                result[1],
                from_candid_opt_n6(this._uploadFile, this._downloadFile, result[2])
            ];
        }
    }
    async getClientProfile(arg0: string): Promise<ClientProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientProfile(arg0);
                return from_candid_ClientProfile_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientProfile(arg0);
            return from_candid_ClientProfile_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientProgress(arg0: string): Promise<Array<WorkoutProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientProgress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientProgress(arg0);
            return result;
        }
    }
    async getClientsForTrainer(): Promise<Array<ClientProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientsForTrainer();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientsForTrainer();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfirmedAppointmentsForClient(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfirmedAppointmentsForClient();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfirmedAppointmentsForClient();
            return result;
        }
    }
    async getExercisePerformanceHistory(arg0: string): Promise<Array<ExercisePerformance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercisePerformanceHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercisePerformanceHistory(arg0);
            return result;
        }
    }
    async getTrainerPtCode(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrainerPtCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrainerPtCode();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutLogsForClient(arg0: string): Promise<Array<WorkoutLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutLogsForClient(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutLogsForClient(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutsForClient(arg0: string): Promise<Array<Workout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutsForClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutsForClient(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logWorkoutCompletion(arg0: WorkoutLog, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logWorkoutCompletion(to_candid_WorkoutLog_n15(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logWorkoutCompletion(to_candid_WorkoutLog_n15(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async registerClient(arg0: string, arg1: string, arg2: string | null, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerClient(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerClient(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async requestAppointment(arg0: string, arg1: string, arg2: Time, arg3: bigint, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestAppointment(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestAppointment(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setClientHeight(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setClientHeight(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setClientHeight(arg0, arg1);
            return result;
        }
    }
    async updateBooking(arg0: bigint, arg1: BookingUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(arg0, arg1);
            return result;
        }
    }
    async updateClientEmail(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClientEmail(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClientEmail(arg0, arg1);
            return result;
        }
    }
    async updateTrainerCode(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTrainerCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTrainerCode(arg0, arg1);
            return result;
        }
    }
    async updateWorkout(arg0: string, arg1: Array<Exercise>, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkout(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkout(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_ClientProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClientProfile): ClientProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutLog_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutLog): WorkoutLog {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    emailOrNickname: [] | [string];
}): {
    username: string;
    emailOrNickname?: string;
} {
    return {
        username: value.username,
        emailOrNickname: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.emailOrNickname))
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    exercises: Array<_ExerciseLog>;
    completed: boolean;
    clientNotes: [] | [string];
    clientUsername: string;
    comments: string;
    workoutName: string;
}): {
    date: string;
    exercises: Array<ExerciseLog>;
    completed: boolean;
    clientNotes?: string;
    clientUsername: string;
    comments: string;
    workoutName: string;
} {
    return {
        date: value.date,
        exercises: value.exercises,
        completed: value.completed,
        clientNotes: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.clientNotes)),
        clientUsername: value.clientUsername,
        comments: value.comments,
        workoutName: value.workoutName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    role: string;
    emailOrNickname: [] | [string];
    codicePT: [] | [string];
}): {
    username: string;
    role: string;
    emailOrNickname?: string;
    codicePT?: string;
} {
    return {
        username: value.username,
        role: value.role,
        emailOrNickname: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.emailOrNickname)),
        codicePT: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.codicePT))
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ClientProfile>): Array<ClientProfile> {
    return value.map((x)=>from_candid_ClientProfile_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutLog>): Array<WorkoutLog> {
    return value.map((x)=>from_candid_WorkoutLog_n13(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutLog_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutLog): _WorkoutLog {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    exercises: Array<ExerciseLog>;
    completed: boolean;
    clientNotes?: string;
    clientUsername: string;
    comments: string;
    workoutName: string;
}): {
    date: string;
    exercises: Array<_ExerciseLog>;
    completed: boolean;
    clientNotes: [] | [string];
    clientUsername: string;
    comments: string;
    workoutName: string;
} {
    return {
        date: value.date,
        exercises: value.exercises,
        completed: value.completed,
        clientNotes: value.clientNotes ? candid_some(value.clientNotes) : candid_none(),
        clientUsername: value.clientUsername,
        comments: value.comments,
        workoutName: value.workoutName
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    role: string;
    emailOrNickname?: string;
    codicePT?: string;
}): {
    username: string;
    role: string;
    emailOrNickname: [] | [string];
    codicePT: [] | [string];
} {
    return {
        username: value.username,
        role: value.role,
        emailOrNickname: value.emailOrNickname ? candid_some(value.emailOrNickname) : candid_none(),
        codicePT: value.codicePT ? candid_some(value.codicePT) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
